name: listcomp
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.2.1
  - pandas=1.0.3
  - pip=20.0.2
  - plotnine=0.6.0
  - python=3.7.6
  - tldextract=2.2.0
  - pip:
    - dscitools==0.1.1
